name: kik_flutter
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.3
  json_annotation: ^1.0.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^1.0.0
  build_runner: ^1.0.0


flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.kik_flutter
    iosBundleIdentifier: com.example.kikFlutter
