# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kik' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kik

  target 'KikTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KikUITests' do
    inherit! :search_paths
     pod 'SnapshotTesting'
  end

end
